# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build data files

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install

    - name: Generate bus bay data
      run: node scripts/generate-bus-bays.mjs

    - name: Generate bus operator data
      run: node scripts/generate-bus-operators.mjs

    - name: Generate platform data
      run: node scripts/generate-rail-platforms.mjs

    - name: Generate station codes
      run: node scripts/generate-rail-station-codes.mjs

    - name: Generate geospatial data
      run: node scripts/kml-to-geojson.mjs

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ':robot: build data files'
        branch: master